sudo: required
dist: trusty
language: node_js

node_js:
  - '4.2'

before_script:
  #- npm install -g codeclimate-test-reporter
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

after_script:
  #TODO: enable publishing code coverage reports
  #- codeclimate < test/coverage/**/lcov.info

notifications:
  # publish build status to IRC channel: #sellect.js
  irc:
    channels:
    - chat.freenode.net#sellect
    on_success: always
    on_failure: always
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
  #TODO: enable publishing build status to gitter.im
  # publish build status to gitter chat room: https://gitter.im/lidia-freitas/sellect.js
  #webhooks:
  #  urls:
  #  - [REPLACE WITH YOUR WEBHOOK URL; https://webhooks.gitter.im/e/XXXXXXXXXXXXXXXX]
  #  on_success: always
  #  on_failure: always
  #  on_start: false

env:
  #- CODECLIMATE_REPO_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  if(process.env.TRAVIS) {
    configuration.browsers = ['Chrome_travis_ci'];
  }
